#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v4
# autospec commit: f4bef72
#
Name     : R-ragg
Version  : 1.3.0
Release  : 36
URL      : https://cran.r-project.org/src/contrib/ragg_1.3.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ragg_1.3.0.tar.gz
Summary  : Graphic Devices Based on AGG
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: R-ragg-lib = %{version}-%{release}
Requires: R-ragg-license = %{version}-%{release}
Requires: R-systemfonts
Requires: R-textshaping
BuildRequires : R-systemfonts
BuildRequires : R-textshaping
BuildRequires : buildreq-R
BuildRequires : freetype-dev
BuildRequires : libpng-dev
BuildRequires : tiff-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
high-performance 2D drawing library. The 'ragg' package provides a set
    of graphic devices based on AGG to use as alternative to the raster
    devices provided through the 'grDevices' package.

%package lib
Summary: lib components for the R-ragg package.
Group: Libraries
Requires: R-ragg-license = %{version}-%{release}

%description lib
lib components for the R-ragg package.


%package license
Summary: license components for the R-ragg package.
Group: Default

%description license
license components for the R-ragg package.


%prep
%setup -q -n ragg
pushd ..
cp -a ragg buildavx2
popd
pushd ..
cp -a ragg buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710613351

%install
export SOURCE_DATE_EPOCH=1710613351
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-ragg
cp %{_builddir}/ragg/LICENSE.note %{buildroot}/usr/share/package-licenses/R-ragg/f380abc818bba52261ccd91e10e0d73b5def4aae || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ragg/DESCRIPTION
/usr/lib64/R/library/ragg/INDEX
/usr/lib64/R/library/ragg/LICENSE
/usr/lib64/R/library/ragg/Meta/Rd.rds
/usr/lib64/R/library/ragg/Meta/features.rds
/usr/lib64/R/library/ragg/Meta/hsearch.rds
/usr/lib64/R/library/ragg/Meta/links.rds
/usr/lib64/R/library/ragg/Meta/nsInfo.rds
/usr/lib64/R/library/ragg/Meta/package.rds
/usr/lib64/R/library/ragg/NAMESPACE
/usr/lib64/R/library/ragg/NEWS.md
/usr/lib64/R/library/ragg/R/ragg
/usr/lib64/R/library/ragg/R/ragg.rdb
/usr/lib64/R/library/ragg/R/ragg.rdx
/usr/lib64/R/library/ragg/help/AnIndex
/usr/lib64/R/library/ragg/help/aliases.rds
/usr/lib64/R/library/ragg/help/figures/README-unnamed-chunk-3-1.png
/usr/lib64/R/library/ragg/help/figures/README-unnamed-chunk-4-1.png
/usr/lib64/R/library/ragg/help/figures/logo.png
/usr/lib64/R/library/ragg/help/paths.rds
/usr/lib64/R/library/ragg/help/ragg.rdb
/usr/lib64/R/library/ragg/help/ragg.rdx
/usr/lib64/R/library/ragg/html/00Index.html
/usr/lib64/R/library/ragg/html/R.css
/usr/lib64/R/library/ragg/tests/testthat.R
/usr/lib64/R/library/ragg/tests/testthat/test-circle.R
/usr/lib64/R/library/ragg/tests/testthat/test-jpeg.R
/usr/lib64/R/library/ragg/tests/testthat/test-line.R
/usr/lib64/R/library/ragg/tests/testthat/test-path.R
/usr/lib64/R/library/ragg/tests/testthat/test-png.R
/usr/lib64/R/library/ragg/tests/testthat/test-polygon.R
/usr/lib64/R/library/ragg/tests/testthat/test-polyline.R
/usr/lib64/R/library/ragg/tests/testthat/test-ppm.R
/usr/lib64/R/library/ragg/tests/testthat/test-raster.R
/usr/lib64/R/library/ragg/tests/testthat/test-rect.R
/usr/lib64/R/library/ragg/tests/testthat/test-text.R
/usr/lib64/R/library/ragg/tests/testthat/test-tiff.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/ragg/libs/ragg.so
/V4/usr/lib64/R/library/ragg/libs/ragg.so
/usr/lib64/R/library/ragg/libs/ragg.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-ragg/f380abc818bba52261ccd91e10e0d73b5def4aae
